### ISSUE TITLE
When referring to a node's configuration file externally, an error occurs if the newline code is LF.

### ISSUE THREAD

**Issue by sig9org** [CiscoDevNet/terraform-provider-cml2#106]
## Symptoms

When creating a node on CML2 from Terraform, you can refer to an external configuration file. An error occurred if the newline code in the configuration file was CRLF.

```sh
cml2_node.dev1: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to cml2_node.dev1, provider
│ "provider[\"registry.terraform.io/ciscodevnet/cml2\"]" produced an unexpected new value:
│ .configuration: was cty.StringVal("hostname dev1\r\n!\r\nend"), but now cty.StringVal("hostname
│ dev1\n!\nend").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

## Environment

The following versions were tested:

- Terraform 1.7.3
- CML2 Provider 0.7.0

## Workaround

If the newline code of the external file is LF, it works correctly.

### main.tf

```terraform
resource "cml2_node" "dev1" {
  lab_id         = cml2_lab.lab1.id
  label          = "dev1"
  nodedefinition = "cat8000v"
  configuration  = file("dev1.txt")
  x              = 0
  y              = 0
} 
```

### dev1.txt

```
hostname dev1
!
end 
```

**Comment by rschmied** [comment]
Thanks for raising this...  I am kind of puzzled right now how to treat this properly.  The `file()` function reads the file with the CR/LF (Windows, I presume) and pushes it to the controller.  The controller, however, returns the same configuration but now with Unix line endings (e.g. just LF).  When Terraform compares the value, it's different, obviously **from a white space / line ending** point of view.  So, raising the "inconsistent result" error is fair.

One obvious (but likely inconvenient) solution is to save the configurations in the way CML expects and returns them.  That is, with LF and not with CR/LF line endings.

**Comment by rschmied** [comment]
I am still not sure what the proper, canonical solution for this is... a workaround when using this on Windows could be to wrap every `file` with a `replace` like so:

```hcl
config = replace(file(var.filename), "\r\n", "\n")
```

It is truly a workaround but it should work -- this will make the config when read from disk using Unix Line feeds and strip out the carriage returns which Windows/DOS adds.

Let me know if this works for you, @sig9org . Thanks!

**Comment by rschmied** [comment]
https://discuss.hashicorp.com/t/cr-lf-vs-lf-handling-with-resource-string-attributes/64999

will try to add the proposed solution from there.
