### ISSUE TITLE
Dynamic creation of unmanaged_switch is limited to 8 interfaces

### ISSUE THREAD

**Issue by thepurplebuffalo** [CiscoDevNet/terraform-provider-cml2#138]
I am attempting to setup an environment for automated testing of my scripts against multiple version of IOS-XE.

I have found that when attaching a variable number of routers to a node of type ```unmanaged_switch``` the switch is limited to 8 ports and will not dynamically allocate any more.

```hcl
terraform {
  required_providers {
    cml2 = {
      source = "registry.terraform.io/ciscodevnet/cml2"
      # Docs:
      # https://registry.terraform.io/providers/ciscodevnet/cml2/latest/docs
    }
  }
}

resource "cml2_lab" "tftest" {
  title = "TF-CML All IOS-XE"
}

data "cml2_images" "images" {
  # no node definition is required for this data source as all images are
  # desired for further filtering.
}

locals {
  # create a list of the node definitions we are interested in:
  desirednodedefinitionlist = ["cat8000v", "csr1000v"]

  # create a list of all of the image definitions:
  imagelist = data.cml2_images.images.image_list

  # create a list of the images that match the desired node definitions:
  filteredimagelist = [for img in data.cml2_images.images.image_list : img
    if contains(local.desirednodedefinitionlist, img.nodedefinition)
  ]

  # create a map of images based on the pre-filtered image list:
  filteredimagemap = { for i, img in local.filteredimagelist : img.id => {
    name        = "r${i + 1}"
    ios_version = img.id
    nodedef     = img.nodedefinition
    x           = 50 * i
    y           = 0
    num         = i + 1
    }
  }
}

resource "cml2_node" "router" {
  # for_each docs: https://developer.hashicorp.com/terraform/language/meta-arguments/for_each
  for_each        = local.filteredimagemap
  lab_id          = cml2_lab.tftest.id
  label           = each.value.name
  nodedefinition  = each.value.nodedef
  x               = each.value.x
  y               = each.value.y
  imagedefinition = each.value.ios_version
}

resource "cml2_node" "CMLMgmt_ExternalConnector" {
  lab_id         = cml2_lab.tftest.id
  label          = "CML Mgmt External Connector"
  nodedefinition = "external_connector"
  x              = 0
  y              = -200
  configuration  = "vlan1234"
}

resource "cml2_node" "CMLMgmt_Switch" {
  lab_id         = cml2_lab.tftest.id
  label          = "CML Mgmt Switch"
  nodedefinition = "unmanaged_switch"
  x              = 0
  y              = -100
}

resource "cml2_link" "CMLMgmt_Switch_to_CMLMgmt_ExternalConnector" {
  lab_id = cml2_lab.tftest.id
  node_a = cml2_node.CMLMgmt_ExternalConnector.id
  node_b = cml2_node.CMLMgmt_Switch.id
}

resource "cml2_link" "CMLMgmt_Switch_to_router" {
  for_each = cml2_node.router
  lab_id   = cml2_lab.tftest.id
  node_a   = cml2_node.CMLMgmt_Switch.id
  node_b   = each.value.id
}

resource "cml2_lifecycle" "top" {
  lab_id     = cml2_lab.tftest.id
}
```

What comes back is the following error:

    │ Error: CML2 Provider Error
    │ 
    │   with cml2_link.CMLMgmt_Switch_to_router["csr1000v-17-03-06"],
    │   on main.tf line 60, in resource "cml2_link" "CMLMgmt_Switch_to_router":
    │   60: resource "cml2_link" "CMLMgmt_Switch_to_router" {
    │ 
    │ Unable to create link, got error: status: 400, {
    │   "description": "Physical configuration of node is locked: b68bc2f5-7872-46a7-9016-3861fbf2b36a ad7af5ab-310b-4adc-a667-0ea86173cfb2.",
    │   "code": 400
    │ }

When I look at the running CML lab I see that 8 of the 8 ports are assigned and connected on the unmanaged switch, but there are more than 8 devices trying to connect to it.  It fails on the 9th connection.

Since the ```interfaces``` field is read-only there doesn't seem to be a way to dynamically expand the capacity of the unmanaged_switch.

Is there a way to specify the number of ports an unmanaged_switch should have at the time of creation?  Based on the CML interface, the maximum appears to be 32 when adjusting it manually (ie: without Terraform).

Thanks

**Comment by rschmied** [comment]
thanks -- i'll look into it

**Comment by rschmied** [comment]
What you see is expected.  Here's why:

If you do  not define any dependencies then the `cml2_lifecycle` resource will start the lab in parallel to all the other resources. This will then lock down these resources so that no more interfaces can be added even if there are more to be created.

You can address this easily by adding a dependency:

```hcl
resource "cml2_lifecycle" "top" {
  depends_on = [cml2_link.CMLMgmt_Switch_to_router]
  lab_id     = cml2_lab.tftest.id
  # state  = "DEFINED_ON_CORE"
}
```

As shown above, an alternative  is to not start the lab immediately but have it in state `DEFINED_ON_CORE`.  This will also work.

**Comment by thepurplebuffalo** [comment]
Ah!  That makes perfect sense.  Thanks!
