### ISSUE TITLE
Improve installation

### ISSUE THREAD

**Issue by Gwynbl31dd** [CiscoDevNet/terraform-provider-cml2#33]
The installation of the local plugin is not very clear.

I had to:

* Use the make file ``make devinstall``
* Modify the path to a valid version (0.5.1-beta.....) to 0.5.1
* Add this piece of config in my main.tf

```
terraform {
    required_providers {
    cml2 = {
      source  = "registry.terraform.io/ciscodevnet/cml2"
      version = ">= 0.0"
    }
  }
}
provider "cml2" {
``` 

All good after

**Comment by rschmied** [comment]
Thanks for the feedback... you should not need to build anything yourself when your intent is to USE the provider... can you clarify whether you wanted to dev or simply use it in a workflow? I've seen that you forked the repo but am not sure what your plan is :grin:

**Comment by Gwynbl31dd** [comment]
I'm a Software engineer at Cisco. I'm tempted to integrate CML with a CI/CD pipeline. I used to do it with simple REST requests, but using terraform is a better idea. About the fork.. I may be able to help if I see a bug.  (I was planning on fixing what I see and sending you a pull request)  :)

**Comment by rschmied** [comment]
Please do so. Generally speaking, I'm looking for feedback how to improve the provider and/or make it more useful in real world scenarios.

**Comment by rschmied** [comment]
closing this... you can always open a new one or provide a PR -- thanks!
