### ISSUE TITLE
Custom initial configuration for Nexus 9000v not working

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-cml2#50]
When deploying a Nexus 9000v using the resource "cml2_node", there is a conflict with the default config with the one that comes by default by the controller.

The plan is to deploy a lab for Nexus POAP so I need the initial default config to be empty.

I'm using CML 2.5 build 5
Image: NXOS 9300v 9.3.8

Code being used:
`resource "cml2_node" "DC-A-Leaf101" {
  lab_id       = cml2_lab.ndfc_demo.id
  label          = "DC-A-Leaf101"
  nodedefinition = "nxosv9000"
      x              = -942
      y              = 60
      configuration = ""
}`

Getting the following error:
`cml2_node.DC-A-Leaf101: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cml2_node.DC-A-Leaf101, provider
│ "provider[\"registry.terraform.io/ciscodevnet/cml2\"]" produced an
│ unexpected new value: .configuration: was cty.StringVal(""), but now
│ cty.StringVal("hostname inserthostname-here\n# workaround for booting to
│ loader> prompt\necho 'from cli import cli' > set_boot.py\necho 'import
│ json' >> set_boot.py\necho 'import os' >> set_boot.py\necho 'import time'
│ >> set_boot.py\necho 'bootimage = json.loads(cli(\"show version |
│ json\"))[\"kick_file_name\"]' >> set_boot.py\necho 'set_boot = cli(\"conf t
│ ; boot nxos {} ; no event manager applet BOOTCONFIG\".format(bootimage))'
│ >> set_boot.py\necho 'i = 0' >> set_boot.py\necho 'while i < 10:' >>
│ set_boot.py\necho '    try:' >> set_boot.py\necho '        save_config =
│ cli(\"copy running-config startup-config\")' >> set_boot.py\necho '
│ break' >> set_boot.py\necho '    except Exception:' >> set_boot.py\necho '
│ i += 1' >> set_boot.py\necho '        time.sleep(1)' >> set_boot.py\necho
│ 'os.remove(\"/bootflash/set_boot.py\")' >> set_boot.py\nevent manager
│ applet BOOTCONFIG\n event syslog pattern \"Configured from vty\"\n action
│ 1.0 cli python bootflash:set_boot.py\n# minimum needed config to login\nno
│ password strength-check\nusername admin role network-admin\nusername admin
│ password cisco role network-admin\nusername cisco role
│ network-admin\nusername cisco password cisco role network-admin\n").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)
`

**Comment by rschmied** [comment]
Thanks for raising this... I am not 100% sure how to handle this at this point as the default configuration is inserted by the controller. In other words, if the configuration of the node is empty, the controller inserts the default configuration.

What is pretty obvious is the fact that default configurations must not cause a provider error. Will need to discuss...
