### ISSUE TITLE
on stopping a lab, the provider gives error 500

### ISSUE THREAD

**Issue by netcicd** [CiscoDevNet/terraform-provider-cml2#74]
I created a lab, updated the configuration with more nodes and wanted to destroy the lab. It looked like it was OK in doing so, but then I got the following error message:
 Error: CML2 Provider Error
│ 
│ Unable to stop node, got error: status: 500, {
│   "description": "The API at /api/v0/labs/aaf9ffaa-c709-453d-9b4e-05584cda6d7a/nodes/f6089288-5bb1-4693-9e5d-b9887a534f4c/state/stop encountered an unexpected error.  Please report this problem to support.",
│   "code": 500
│ }
As requested: the report :)

re-issuing destroy finished the destruction.
Labs can be provided off-line

**Comment by netcicd** [comment]
Have not seen this in CML 2.6 so far

**Comment by rschmied** [comment]
This was an issue with parallel delete requests for both nodes and their links. Fixed in 2.6.1 / SIMPLE-5368. 

> The fix was tested on a 25-node Terraform plan by repeatedly creating and tearing it down with 30s pauses, with ~800 repeats without a destroy failure.
