### ISSUE TITLE
On updating a lab with more nodes, the lab needs to be destroyed first

### ISSUE THREAD

**Issue by netcicd** [CiscoDevNet/terraform-provider-cml2#75]
When you expand a lab with more nodes in Design mode, creation fails with: 

│ Error: CML2 Provider Error
│ 
│   with module.pods.module.pod_cml[0].cml2_lifecycle.top,
│   on modules/cml/pod_cml/main.tf line 29, in resource "cml2_lifecycle" "top":
│   29: resource "cml2_lifecycle" "top" {
│ 
│ unexpected node state BOOTED
╵
destroying the lab and applying after that works as expected.

**Comment by netcicd** [comment]
Still present in 2.6. I expect a node to be stopped, destroyed and re-deployed

**Comment by rschmied** [comment]
I added an integration test which specifically tests this and I can't reproduce. The test goes like:

- start lab, ext-conn, ums, two nodes and three links
- wait for convergence (BOOTED)
- add another node and link to ums
- wait for convergence (BOOTED)

this sequence works. If this re-appears then please open a new issue which has specific reproduction instructions. Ideally with common node types (Alpine) and a Terraform file that results in the error.
