### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by netcicd** [CiscoDevNet/terraform-provider-cml2#76]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.pods.module.pod_cml[0].cml2_lifecycle.App-PoD, provider "provider[\"registry.terraform.io/ciscodevnet/cml2\"]" produced an unexpected new value: .state: was
│ cty.StringVal("STARTED"), but now cty.StringVal("DEFINED_ON_CORE").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.tenants.module.tenant_cml[0].cml2_lifecycle.Tenant, provider "provider[\"registry.terraform.io/ciscodevnet/cml2\"]" produced an unexpected new value: .state: was
│ cty.StringVal("STARTED"), but now cty.StringVal("DEFINED_ON_CORE").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by netcicd** [comment]
This one is consistent on every apply.

**Comment by netcicd** [comment]
Have not seen this in CML 2.6 so far

**Comment by rschmied** [comment]
will close this -- if it re-appears then need to open a new issue. In general, there's likely still some lingering issues with state changes, especially when lab/node simulation state or topology data is changed after initial deployment.
