### ISSUE TITLE
Link shows as Defined on Core in terraform, but is invisible in CML

### ISSUE THREAD

**Issue by netcicd** [CiscoDevNet/terraform-provider-cml2#82]
When creating my lab I have one link which is defined on core, but does not show up in the lab. When you try to connect the node in the lab, the interface is available, but when connecting it appears not to be and the link cannot be created as the interface is is use. Is the case on both ends of the link. 

Lab available upon request.

**Comment by netcicd** [comment]
Have not seen this in CML 2.6 so far

**Comment by rschmied** [comment]
will close this as it's not showing in 2.6 anymore. Most likely a fix on the back-end which made this go away.
