### ISSUE TITLE
deprecate lifecycle.elements in favor of depends_on

### ISSUE THREAD

**Issue by rschmied** [CiscoDevNet/terraform-provider-cml2#94]
Apparently, they are doing the same thing: creating state dependencies. At the time of creating the `elements` property, I was simply not aware of `depends_on` which would have been the obvious choice as it does exactly the same thing, built-in.

Need to investigate the ramification when declaring `elements` obsolete/deprecated and how this would impact users... I guess it would not but want to be clear upfront.

**Comment by rschmied** [comment]
tagging @netcicd and @tiagosil-cisco

**Comment by netcicd** [comment]
I will see what I use when I am back next week. Have a good newyear

**Comment by myref** [comment]
I extensively use elements as per your blog. Will it just be a replacement of the elements keyword with depends_on? If so I will try to test

**Comment by rschmied** [comment]
yes... everywhere where you use an `elements` list it should be possible to simply replace it with an `depends_on` list. They do the same thing but `depends_on` is built into TF.

**Comment by tiagosil-cisco** [comment]
Maybe I wasn't using "elements" correctly, but I thought that we could have different "cml2_lifecycle" resources to manage different nodes/links in the same lab. Let's say, we build a big topology with two datacenter but I want to control each one independently.

**Comment by rschmied** [comment]
@tiagosil-cisco I guess you were. Are you saying that you had multiple lifecycle resources in the same TF? If so, then I think that there should be some code which would restrict the number of lifecycle resources to ONE or ZERO. Not even sure what the implications would be if there's multiple LC resources...!?

**Comment by rschmied** [comment]
https://developer.hashicorp.com/terraform/plugin/framework/deprecations

need to implement this...

**Comment by rschmied** [comment]
addressed by PR #130
